### ISSUE TITLE
Link Relation Type

### ISSUE THREAD

**Issue by dret** [mikewest/error-reporting#5]
https://github.com/dret/I-D/blob/master/issues-link-rel/draft-wilde-issues-link-rel-00.txt (not yet submitted) is a similar idea, but instead of defining an HTTP header field, it defines a link relation type, so that the reporting target can be included as a link in any hypermedia format.
do you think that there is some relation between these ideas? if yes, would it make sense to somehow coordinate these proposals? one simple way would be to cross-reference, another one would be to align them somehow, and a third one would be to merge them.

**Comment by dret** [comment]
created https://github.com/dret/I-D/issues/22 in the "A Link Relation Type for Issue Management" draft repo.

**Comment by igrigorik** [comment]
Hmm, couple of different threads here: 
- Note that CSP and NEL intentionally disallow registering reporting endpoints via `<meta>` - e.g. http://www.w3.org/TR/CSP2/#report_uri. This is a security precaution: bad scripts can't override the reporting origin and redirect/block reports; with header approach you'd have to also compromise the server. 
- The primary use case for this API is for UA generated reports, not for collecting user feedback.

**Comment by mikewest** [comment]
I agree with @igrigorik; this seems like a related, but quite distinct proposal. I'm happy to add a reference to that draft in this document. I'll do so shortly.

**Comment by mikewest** [comment]
Note: a proposal like yours could certainly use this reporting framework, just like any other feature. That is, instead of sending a `Link:` header, you could send some other header that defined the reporting endpoint group to which user-generated reports should be sent, as well as their format. This spec is fairly agnostic to the way the report is generated, it simply defines a mechanism by which a JSON blob will be delivered to a server. It would save you some boilerplate in your document, and clarify the relation with things like Fetch.

I skimmed the I-D again, and I don't think it's far enough along to link from this doc. I do think it's an interesting proposal, however. I'll be interested in seeing it polished up and submitted for consideration. :)

Closing this out; let's move any further conversation to w3c/reporting. :)

**Comment by dret** [comment]
On 2015-12-07 11:04 , Ilya Grigorik wrote:

> - The primary use case for this API is for UA generated reports, not
>   for collecting user feedback.

from the perspective of the link relation type, it does not really 
matter who is using/generating the reports (whether it's the user agent 
or the user). all we are concerned about is how to discover the URI that 
reporting is supposed to go to.

how that reporting is done (by whom and what it is about) is a different 
issue and a question of the context of where the link relation is used 
and discovered.
